version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8000
      - 7913
    ports:
      - 8000:8000
    volumes:
      - ./django_chat:/src