version: '3'

services:
  server:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 8000
      - 7913
    ports:
      - 8000:8000
    volumes:
      - ./django_chat:/src
      - ./django_bot:/django_bot

  rabbitmq:
    restart: always
    image: rabbitmq:3.7-management-alpine
    hostname: rabbitmq
    expose:
      - 5672
    ports:
      # HTTP management UI
      - 15672:15672